### ISSUE TITLE
编译错误

### ISSUE THREAD

**Issue by jiangzhhhh** [baesky/WPF-Ray-Tracing#1]
1>------ 已启动生成: 项目: WPFRayTracing, 配置: Release Any CPU ------

1>C:\Users\jiangzh\Desktop\WPF-Ray-Tracing-master\WPFRayTracing\WPFRayTracing\World.cs(94,37,94,39): error CS1061: 'PerfactSpecular' does not contain a definition for 'Ks' and no extension method 'Ks' accepting a first argument of type 'PerfactSpecular' could be found (are you missing a using directive or an assembly reference?)

1>C:\Users\jiangzh\Desktop\WPF-Ray-Tracing-master\WPFRayTracing\WPFRayTracing\World.cs(95,37,95,40): error CS1061: 'PerfactSpecular' does not contain a definition for 'Exp' and no extension method 'Exp' accepting a first argument of type 'PerfactSpecular' could be found (are you missing a using directive or an assembly reference?)

1>C:\Users\jiangzh\Desktop\WPF-Ray-Tracing-master\WPFRayTracing\WPFRayTracing\World.cs(106,36,106,38): error CS1061: 'PerfactSpecular' does not contain a definition for 'Ks' and no extension method 'Ks' accepting a first argument of type 'PerfactSpecular' could be found (are you missing a using directive or an assembly reference?)

1>C:\Users\jiangzh\Desktop\WPF-Ray-Tracing-master\WPFRayTracing\WPFRayTracing\World.cs(107,36,107,39): error CS1061: 'PerfactSpecular' does not contain a definition for 'Exp' and no extension method 'Exp' accepting a first argument of type 'PerfactSpecular' could be found (are you missing a using directive or an assembly reference?)

1>C:\Users\jiangzh\Desktop\WPF-Ray-Tracing-master\WPFRayTracing\WPFRayTracing\Light\EnviromentLight.cs(8,26,8,29): warning CS0649: Field 'EnviromentLight.Mat' is never assigned to, and will always have its default value null

1>C:\Users\jiangzh\Desktop\WPF-Ray-Tracing-master\WPFRayTracing\WPFRayTracing\Light\EnviromentLight.cs(9,24,9,34): warning CS0649: Field 'EnviromentLight.SamplerRef' is never assigned to, and will always have its default value null
========== 生成: 成功 0 个，失败 1 个，最新 0 个，跳过 0 个 ==========

**Comment by baesky** [comment]
Please use Preview Brach, I will fix master ASAP.
